
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx:tar
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - target: 443
        published: 443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      always

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:tar
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart:
      always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:tar
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      always

  redis: # ------------------------------------------------
    build: requirements/bonus/redis
    container_name: redis
    image: redis:tar
    networks:
      - inception
    restart:
      always

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    image: ftp:tar
    env_file:
      - .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      always

  static:
    build: requirements/bonus/static
    container_name: static
    image: static:tar
    ports:
      - target: 1200
        published: 1200
    restart:
      always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    image: adminer:tar
    ports:
      - target: 8000
        published: 8000
    networks:
      - inception
    restart:
      always

  rsync:
    build: requirements/bonus/rsync
    container_name: rsync
    image: rsync:tar
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - rsync:/home/backup/
    networks:
      - inception
    restart:
      always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/tamehri/data/wordpress
  db:
    name: db
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/tamehri/data/database

  rsync:
    name: rsync
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/tamehri/data/backup

networks:
  inception:
    name: inception
    driver: bridge
